name: Prepare Chrome Web Store Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set outputs
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "sha_long=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Install dependencies
      working-directory: chrome
      run: npm install

    - name: Extract version from manifest.json
      id: get-version
      run: |
        VERSION=$(jq -r '.version' chrome/manifest.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build project
      working-directory: chrome
      run: npm run build

    - name: Create zip file
      run: |
        mkdir -p chrome-build
        cp -r chrome/* chrome-build/
        rm -rf chrome-build/node_modules chrome-build/src chrome-build/package-lock.json chrome-build/package.json
        cd chrome-build
        zip -r ../github-jira-linker-${{ env.VERSION }}.zip .
        ls

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      run: |
            gh release create "build/${{env.VERSION}}" --generate-notes --prerelease --target "${{ steps.vars.outputs.sha_long }}" --title "${{env.VERSION}}" "github-jira-linker-${{ env.VERSION }}.zip#${{env.VERSION}} package" 
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
